# A Importância do NumPy na Ciência de Dados e Computação Científica

NumPy (Numerical Python) é uma biblioteca fundamental para computação científica em Python. Ele fornece:
- Objetos de array multidimensionais de alto desempenho
- Ferramentas para trabalhar com esses arrays
- Funções matemáticas otimizadas

Vamos explorar por que o NumPy é tão importante e mostrar alguns exemplos práticos.

## Por que o NumPy é importante?

1. **Desempenho**: Operações vetorizadas são muito mais rápidas que loops em Python puro
2. **Eficiência de memória**: Arrays NumPy ocupam menos espaço que listas Python
3. **Funcionalidades avançadas**: Álgebra linear, transformadas de Fourier, geração de números aleatórios
4. **Base para outras bibliotecas**: Pandas, SciPy, scikit-learn e matplotlib são construídos sobre NumPy
5. **Interface unificada**: Sintaxe consistente para operações com arrays

In [ ]:
# Importando Blibiotecas

import numpy as np
import time
import sys

In [ ]:
# Exemplo 1: Comparação de desempenho

py_list = list(range(1000000))
np_array = np.arange(1000000)

# Soma com Python
start = time.time()
sum_py = sum(py_list)
py_time = time.time() - start

# Soma com NumPy
start = time.time()
sum_np = np.sum(np_array)
np_time = time.time() - start

print(f"Tempo Python: {py_time:.5f} segundos")
print(f"Tempo NumPy: {np_time:.5f} segundos")
print(f"NumPy foi {py_time/np_time:.1f} vezes mais rápido!")

Tempo Python: 0.04754 segundos
Tempo NumPy: 0.00102 segundos
NumPy foi 46.6 vezes mais rápido!


In [ ]:
# Exemplo 2: Eficiência de memória
# Vamos comparar o consumo de memória entre listas e arrays NumPy

print(f"Tamanho da lista Python: {sys.getsizeof(py_list)} bytes")
print(f"Tamanho do array NumPy: {sys.getsizeof(np_array)} bytes")

Tamanho da lista Python: 8000056 bytes
Tamanho do array NumPy: 4000112 bytes


In [ ]:
# Operações matemáticas

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print("Soma:", a + b)
print("Multiplicação:", a * b)
print("Exponenciação:", a ** 2)
print("Seno:", np.sin(a))

In [ ]:
#Teste dentro do array

arr = np.array([1, 2, 3, 4])
result_where = np.where(arr > 2, 'Maior', 'Menor')

In [ ]:
# Empilha arrays como colunas
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result_stack = np.column_stack((a, b))

In [ ]:
# Operações matriciais

# Criando matrizes
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Multiplicação de matrizes:\n", np.dot(A, B))
print("Determinante de A:", np.linalg.det(A))
print("Inversa de A:\n", np.linalg.inv(A))

In [ ]:
# NumPy oferece maneiras poderosas de selecionar dados

arr = np.arange(1, 26).reshape(5, 5)
print("Array original:\n", arr)

# Selecionando linhas e colunas
print("Primeira linha:", arr[0])
print("Última coluna:", arr[:, -1])

# Seleção condicional
print("Valores maiores que 10:", arr[arr > 10])

In [ ]:
#Operações entre arrays de diferentes tamanhos

a = np.array([1, 2, 3])
b = 2  # Escalar

print("Broadcasting (a + b):", a + b)


matrix = np.ones((3, 3))

print(matrix)
row = np.array([1, 2, 3])

print("Matrix + row:\n", matrix + row)

Broadcasting (a + b): [3 4 5]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrix + row:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
# Funções Matemáticas Universais

print("Seno:", np.sin(a))
print("Cosseno:", np.cos(a))
print("Exponencial:", np.exp(a))
print("Logaritmo:", np.log(a))
print("Raiz quadrada:", np.sqrt(a))

Seno: [0.84147098 0.90929743 0.14112001]
Cosseno: [ 0.54030231 -0.41614684 -0.9899925 ]
Exponencial: [ 2.71828183  7.3890561  20.08553692]
Logaritmo: [0.         0.69314718 1.09861229]
Raiz quadrada: [1.         1.41421356 1.73205081]


In [ ]:
# Operações de Redução (ao longo do array)

print("Soma total:", np.sum(a))
print("Produto total:", np.prod(a))
print("Média:", np.mean(a))
print("Desvio padrão:", np.std(a))
print("Valor máximo:", np.max(a))
print("Índice do máximo:", np.argmax(a))
print("Valor mínimo:", np.min(a))

Soma total: 6
Produto total: 6
Média: 2.0
Desvio padrão: 0.816496580927726
Valor máximo: 3
Índice do máximo: 2
Valor mínimo: 1


In [ ]:
# Comparações e Operações Lógicas

print("Comparação:", a > 2)
print("Filtro:", a[a > 2])
print("AND lógico:", (a > 1) & (a < 4))

# Exercícios com NumPy - Operações Simples com Vetores e Matrizes

## Exercício 1: Cálculo de Média Ponderada

Você é professor de uma disciplina e precisa calcular a nota final dos alunos usando um sistema de pesos diferentes para cada avaliação.

Dados:
- Notas de um aluno: `[7.5, 8.0, 6.5, 9.0]` (quatro avaliações)
- Pesos respectivos: `[0.2, 0.3, 0.2, 0.3]`

**Sua tarefa:**
1. Crie dois arrays NumPy com os dados fornecidos
2. Calcule a média ponderada usando operações vetorizadas
3. Arredonde o resultado para 1 casa decimal
4. Exiba o resultado final

**Dica:**  
Lembre-se que média ponderada = Σ(nota × peso) / Σ(pesos)

In [4]:
#Exercício 1
import numpy as np

aluno = np.array([7.5, 8.0, 6.5, 9.0])
peso = np.array([0.2, 0.3, 0.2, 0.3])
notas = (peso * aluno)
print(f"Notas: {notas} Soma: {np.sum(notas)}")



Notas: [1.5 2.4 1.3 2.7] Soma: 7.9


## Exercício 2: Conversão de Temperaturas

Você está trabalhando com dados meteorológicos e precisa converter uma série de temperaturas de Celsius para Fahrenheit.

Dados:
- Temperaturas em Celsius: `[0, 10, 20, 30, 40]`

**Sua tarefa:**
1. Crie um array NumPy com as temperaturas em Celsius
2. Aplique a fórmula de conversão:  
   `Fahrenheit = (Celsius × 9/5) + 32`
3. Crie um novo array com as temperaturas convertidas
4. Exiba ambos os arrays (Celsius e Fahrenheit) para comparação

**Dica:**  
NumPy permite aplicar operações matemáticas a arrays inteiros sem necessidade de loops.

In [ ]:
#Exercício 2

temp = np.array([0, 10, 20, 30, 40])




Exercício 3: Sistema de Pontuação de Atividades Físicas
Você está desenvolvendo um sistema de acompanhamento de atividades físicas que registra:

Quantidade de minutos de exercício por dia
Pontos conquistados (cada minuto = 1 ponto)
Bônus diário (5 pontos para dias com >30 minutos)
Dados da última semana:

Segunda: 25 min Terça: 40 min Quarta: 30 min Quinta: 55 min Sexta: 20 min Sábado: 60 min Domingo: 45 min

Crie uma matriz NumPy 7x3 (dias × dados) contendo:

Coluna 1: minutos de exercício
Coluna 2: pontos base (1 por minuto)
Coluna 3: bônus (5 pontos se minutos >30)
Calcule:

Total de minutos na semana
Total de pontos (base + bônus)
Dia com maior atividade física

In [ ]:
#Exercício 3


